name: geopandas
channels:
  - defaults
  - conda-forge
dependencies:
  - contextily=1.1.0
  - geopandas=0.9.0
  - jupyterlab=3.1.7
  - mapclassify=2.4.3
  - pip=21.2.4
  - python=3.8.11
  - spyder=5.0.5
